### ISSUE TITLE
[BUG]The GUI application tries to run endlessly.

### ISSUE THREAD

**Issue by Adi900696** [Dadangdut33/Speech-Translate#51] opened 2023-11-09 07:20 UTC
When you try to start the application, it loads endlessly.  1 CPU thread is constantly busy. An attempt to delusional CPU and GPU versions, trying to run 1.3.0 and 1.3.1, trying to run on different computers (1: R7 4800h and RTX2060 and the second i7-3630qm and hd4000/Gt730m. Python 3.10.10 was installed on the computers (The one with  installer), and then reinstalled on 3.11.6 (also Installer) and it didn't help. Ffmpeg added. Cmd reports the presence of ffmpeg and python. Old versions worked without any problems even without Python installed on the computer.
![20231109_081221](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/0afa0579-7c92-4c72-9c07-49b78f0e927c)
![20231109_082716](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/eecd4854-d527-413c-8c3c-a3e605df781e)
I have prebuilt binary version.

**Comment by Dadangdut33** [comment] 2023-11-09 08:02
can you share the log? it should be located in the installation folder in lib/speech_translate/log

**Comment by Dadangdut33** [comment] 2023-11-09 08:10
i think i might now what caused the problem, i'll try to fix it real quick

**Comment by Adi900696** [comment] 2023-11-09 08:22
[2023-11-09 09-06-24.log](https://github.com/Dadangdut33/Speech-Translate/files/13305634/2023-11-09.09-06-24.log)
Logi:

**Comment by Dadangdut33** [comment] 2023-11-09 08:35
> Logs: [2023-11-09 09-06-24.log](https://github.com/Dadangdut33/Speech-Translate/files/13305634/2023-11-09.09-06-24.log) - Intel [2023-11-09 07-58-49.log](https://github.com/Dadangdut33/Speech-Translate/files/13305676/2023-11-09.07-58-49.log) - Amd/RTX2060 From what I see, everything stops at the process of applying a new theme at startup.

yea it seems that the splash screen caused the app to froze, i have tried replicating it on my other device and got the same result like yours. That's why i'll probably remove it after this.

**Comment by Dadangdut33** [comment] 2023-11-09 09:15
the splash screen is really the cause of it, thanks for reporting the bug. I'm currently building the next version right now and will upload it as soon as its done

**Comment by Dadangdut33** [comment] 2023-11-09 10:31
Fixed in 1.3.2 thanks for the bug report! :D

**Closed by Dadangdut33** 2023-11-09 10:31 UTC
Labels: bug
