### ISSUE TITLE
[BUG] Hangs on stop recording

### ISSUE THREAD

**Issue by FerriteGiant** [Dadangdut33/Speech-Translate#40] opened 2023-06-10 19:45 UTC
**Describe the bug**
Seems to start a recording just fine, but then hangs after clicking "stop".

**To Reproduce**
1. Install release 1.2.3 on Windows 10
2. Download model (tried 3)
3. Click Record Mic
4. Record a few seconds of speaking
5. Click Stop
6. Says "Stopping..." but never progresses and no indication is shown in console that stop was clicked. App hangs while using 8% of CPU and 5 GB of ram (on tiny model). Only way to stop is to force quit.

**Expected behavior**
Recording should stop and then audio should be processed.

**Screenshots**
![image](https://github.com/Dadangdut33/Speech-Translate/assets/4928288/0a08e871-0ffd-4503-88f1-31746f9f482d)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (build: 19044.2846)
 - Python Version 3.9.2

**Additional context**
Importing an mp3 works as expected.

**Comment by Dadangdut33** [comment] 2023-08-03 16:43
may i know the hardware detail more, are you using gpu?

**Comment by Dadangdut33** [comment] 2023-09-08 17:42
i think i found out the cause of the problem, this should be fixed in the next release. Thanks for the notice 👍

**Comment by Dadangdut33** [comment] 2023-11-07 17:42
Fixed in 1.3.0 release

**Closed by Dadangdut33** 2023-11-07 17:42 UTC
Labels: bug, fixed in dev branch
