### ISSUE TITLE
The size of tensor a (16) must match the size of tensor b (5) atnon-singleton dimension 3

### ISSUE THREAD

**Issue by yslion** [Dadangdut33/Speech-Translate#31] opened 2023-04-20 02:26 UTC
![image](https://user-images.githubusercontent.com/4454836/233241731-e424735d-a119-48dd-8a31-e7d435c5bd6b.png)

The size of tensor a (16) must match the size of tensor b (5) atnon-singleton dimension 3
what's wrong

**Comment by Dadangdut33** [comment] 2023-04-20 10:08
Try to set auto channels and auto sample rate in the setting

**Comment by Dadangdut33** [comment] 2023-04-21 16:22
I honestly couldn't figure out what is wrong here, it might be related to the device because i tried on my mic and headphone and it is working just fine. Have you tried another mic / device ?

**Comment by jinan-tw** [comment] 2023-04-22 00:45
I have tested on other devices, also I'm using Windows 11. 
When encoutering errors, I close the app, the progress seem not to be killed, and keep the GPU memory getting use.
![image](https://user-images.githubusercontent.com/21107283/233752656-10931089-f48b-45b8-9f89-7ad2da21da0c.png)

**Comment by kelvincht** [comment] 2023-04-22 09:41
Got the same issue.

In my case, if Whisper Translation is used, regardless keeping transcript or not. It will have the same error in the first few seconds.
The size of tensor a (x) must match the size of tensor b (y)

If I just use transcript without translation. No errors

If I use transcript in Whisper, and translate using Google translate. No errors

**Comment by kelvincht** [comment] 2023-04-22 09:50
2023-04-21 09:13:44,485 - ERROR - The size of tensor a (13) must match the size of tensor b (5) at non-singleton dimension 3 (Record.py:720) [Thread-6 (rec_realTime)]
Traceback (most recent call last):
  File "speech_translate\utils\Record.py", line 588, in rec_realTime

![image](https://user-images.githubusercontent.com/14211525/233776656-94bced0a-3406-4317-a5a2-3c64b4c85f03.png)

Some suggestion from Whisper AI community

https://github.com/openai/whisper/discussions/951

`Hi, it appears that you're calling the model from different threads. The model is not equipped for that, mainly because of the kv cache logic using the hooks. I'd suggest keep using the lock, if that's not too much of a slowdown.`

**Comment by kelvincht** [comment] 2023-04-22 10:19
I guess the issue is in Record.py, you can't call two model.transcribe concurrently. It need some kind of lock between them, or have them in one thread.

**Comment by kelvincht** [comment] 2023-04-22 10:34
Ok, I did a hacky fix using a Thread.lock acquire/release between model.transcribe in line 5xx and 7xx in Record.py

It works... you may want to implement it more elegantly

![image](https://user-images.githubusercontent.com/14211525/233778755-361748ef-04bc-4f1e-ab56-78db7421750e.png)


![image](https://user-images.githubusercontent.com/14211525/233778734-92b5320b-0d5c-4339-936e-c2c53cf748f0.png)


![image](https://user-images.githubusercontent.com/14211525/233778596-a0591aaa-d139-44a9-a716-c2b2ea32a8b5.png)

**Comment by PawelGu** [comment] 2023-08-06 13:32
I'm having the same problem and wanted to edit record.py.
Seems I'm too dumb or just can't find the file.
I'm on Windows 10 and there is neither a utils directory nor the python file.
Can anybody help me? The online translation integration is nice but so much slower and eeven seems less accurate...

**Comment by Dadangdut33** [comment] 2023-08-23 19:26
> Ok, I did a hacky fix using a Thread.lock acquire/release between model.transcribe in line 5xx and 7xx in Record.py
> 
> It works... you may want to implement it more elegantly
> 
> ![image](https://user-images.githubusercontent.com/14211525/233778755-361748ef-04bc-4f1e-ab56-78db7421750e.png)
> 
> ![image](https://user-images.githubusercontent.com/14211525/233778734-92b5320b-0d5c-4339-936e-c2c53cf748f0.png)
> 
> ![image](https://user-images.githubusercontent.com/14211525/233778596-a0591aaa-d139-44a9-a716-c2b2ea32a8b5.png)
> 
> ![image](https://user-images.githubusercontent.com/14211525/233778893-5de5d5a3-8524-46b2-8826-f2dbaac4325a.png)

Thanks for the help @kelvincht <3 i have added it to the code

**Comment by EllyKher** [comment] 2023-11-02 17:14
@Dadangdut33 Unfortunately the issue is still there. 
`RuntimeError: The size of tensor a (12) must match the size of tensor b (5) at non-singleton dimension 3`

I have also set auto channels and auto sample rate in the setting.. Nothing changed. 

I am using the last version released.

**Comment by Dadangdut33** [comment] 2023-11-02 17:37
> @Dadangdut33 Unfortunately the issue is still there. `RuntimeError: The size of tensor a (12) must match the size of tensor b (5) at non-singleton dimension 3`
> 
> I have also set auto channels and auto sample rate in the setting.. Nothing changed.
> 
> I am using the last version released.

Its fixed on 1.3.0 which is not released yet. I will try to release it maybe tomorrow or the day after it

**Comment by Dadangdut33** [comment] 2023-11-07 17:41
Fixed in 1.3.0 release

**Closed by Dadangdut33** 2023-11-07 17:41 UTC
Labels: bug, fixed in dev branch
